spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: Karthik@007

logging:
  level:
    com.enterprise.banking.transaction: DEBUG
    org.hibernate.SQL: DEBUG
